/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
const _ = require('lodash')

function solution(maxTerm) {
  const fibs = generateFibonacci(maxTerm)
  const evenFibNumbers = fibs.filter(number => number % 2 === 0)
  return _.sum(evenFibNumbers)
}

function generateFibonacci(maxTerm) {
  let first = 1
  let second = 2
  let third
  const fib = [first]


  while (second <= maxTerm) {
    third = first + second
    first = second
    second = third

    fib.push(first)
  }

  return fib

}
console.log(solution(4000000))
